version: '2'

services:
  gogsmodified:
    scale: 1

catalog:
  name: "GogsModified"
  version: "v0.0.3"
  description: "A copy of the gogs template from community-catalog, with modifications"
  uuid: gogs-modified-0
  minimum_rancher_version: v0.51.0
  questions:
    - variable: http_port
      description: "http port to access gogs webui"
      label: "Http Port"
      required: true
      default: "10080" 
      type: "int"
    - variable: ssh_port
      description: "ssh port to access gogs cli"
      label: "SSH Port"
      required: true
      default: "222"
      type: "int"
    - variable: gogs_hostname
      description: "gogs hostname"
      label: "Gogs hostname"
      required: true
      default: ""
      type: "string"
